source 'git@192.168.28.216:zhangyao/TZSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'RightMuneTabel_Example' do
  pod 'RightMuneTabel', :path => '../'

  target 'RightMuneTabel_Tests' do
    inherit! :search_paths

    
  end
end
